#!/usr/bin/python3
import pyfiglet
import sys
import socket
from datetime import datetime

def banner():
    banner = pyfiglet.figlet_format("ZMX")
    print(banner)

def scanHost(ip, startPort, endPort):
    banner()
    print("[+] Starting port scan on host %s" % ip)
    scan(ip, startPort, endPort)

def scan(ip, startPort, endPort):
    for port in range(startPort, endPort+1):
        try:
            tcp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            if not tcp.connect_ex((ip, port)):
                print("[+] %s:%d Open" % (ip, port))
                tcp.close()
        except Exception:
            pass


if __name__ == "__main__":
    socket.setdefaulttimeout(0.01)

    if len(sys.argv) < 4:
        banner()
        print("Usage: zmx <IP address> <start port> <end port>")
    elif len(sys.argv) >= 4:
        ip = sys.argv[1]
        startPort = int(sys.argv[2])
        endPort = int(sys.argv[3])
    if len(sys.argv) == 4:
        scanHost(ip, startPort, endPort)
