#!/bin/bash

BIN_DIR="/usr/bin"
MAIN_FILE="zmx"

chmod +x $MAIN_FILE

clear

echo "--   ZMX Installer  --"
echo ""
echo "path: (default /usr/bin)"
sleep 0.1
echo "name: (default zmx)"

sleep 1

sudo mv $MAIN_FILE $BIN_DIR

sleep 3

pip3 install -r requirements.txt -q

echo ""
echo "--       Done        --"
